-- https://school.programmers.co.kr/learn/courses/30/lessons/131118

-- 서울에 있는 식당 목록
WITH SEOUL AS (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울특별시%' OR ADDRESS LIKE '서울시%'
), -- 서울에 있는 식당에서 평점 계산
SEOUL_REVIEW AS (
    SELECT S.REST_ID, S.REST_NAME, S.FOOD_TYPE, S.FAVORITES, S.ADDRESS, ROUND(SUM(RR.REVIEW_SCORE)/COUNT(S.REST_ID),2) AS SCORE
    FROM SEOUL AS S JOIN REST_REVIEW AS RR ON S.REST_ID = RR.REST_ID
    GROUP BY S.REST_ID
)

SELECT * FROM SEOUL_REVIEW
ORDER BY SCORE DESC, FAVORITES DESC