-- 코드를 입력하세요
WITH OS AS(
    SELECT USER_ID,SALES_AMOUNT,YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
), UI AS (
    SELECT USER_ID, GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
)

SELECT OS.YEAR,OS.MONTH,UI.GENDER,COUNT(DISTINCT UI.USER_ID) AS USERS
FROM UI JOIN OS ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR,MONTH,GENDER

