-- 코드를 입력하세요
WITH F AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
), S AS(
    SELECT CAR_ID, MONTH(START_DATE) AS START, MONTH(END_DATE) AS END
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (SELECT CAR_ID FROM F) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
), T AS(
    SELECT START AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
    FROM S
    GROUP BY MONTH(START_DATE), CAR_ID
)


SELECT * 
FROM T
ORDER BY MONTH, CAR_ID DESC