-- 코드를 작성해주세요
WITH F AS (
    SELECT EMP_NO, SUM(SCORE)/ COUNT(EMP_NO) AS AVG
    FROM HR_GRADE
    GROUP BY EMP_NO
), S AS (
    SELECT F.EMP_NO, F.AVG, HE.EMP_NAME, HE.SAL
    FROM F JOIN HR_EMPLOYEES AS HE ON F.EMP_NO = HE.EMP_NO
), T AS(
    SELECT EMP_NO, EMP_NAME, AVG,
    CASE 
        WHEN AVG >= 96 THEN 'S'
        WHEN 90 <= AVG AND AVG < 96 THEN 'A'
        WHEN 80 <= AVG AND AVG < 90 THEN 'B'
        ELSE 'C'
    END AS GRADE,SAL
    FROM S
), K AS (
    SELECT EMP_NO, EMP_NAME, GRADE,
    CASE 
        WHEN GRADE = 'S' THEN SAL * 0.2
        WHEN GRADE = 'A' THEN SAL * 0.15
        WHEN GRADE = 'B' THEN SAL * 0.1
        ELSE SAL * 0
    END AS BONUS
    FROM T
)

SELECT * 
FROM K
ORDER BY EMP_NO