WITH A AS (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
), B AS (
    SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, BOOK.BOOK_ID, BOOK.PRICE
    FROM AUTHOR
    JOIN BOOK ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
)

SELECT B.AUTHOR_ID, B.AUTHOR_NAME, B.CATEGORY, SUM(A.TOTAL * B.PRICE) AS TOTAL_SALES
FROM A
JOIN B ON A.BOOK_ID = B.BOOK_ID
GROUP BY B.AUTHOR_ID, B.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;