-- 코드를 작성해주세요

WITH T AS(
    SELECT ID, FISH_TYPE, 
    CASE
        WHEN LENGTH IS NULL THEN 10
        WHEN LENGTH <= 10 THEN 10
        ELSE LENGTH
    END AS LENGTH,TIME
    FROM FISH_INFO
), F AS (
    SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH ,FISH_TYPE
    FROM T
    GROUP BY FISH_TYPE
    HAVING SUM(LENGTH) / COUNT(ID) >= 33
)

SELECT * 
FROM F
ORDER BY FISH_TYPE
