-- 코드를 작성해주세요
WITH F AS (
    SELECT PARENT_ITEM_ID AS PID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
),S AS (
    SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
    FROM ITEM_INFO AS II LEFT JOIN F ON II.ITEM_ID = F.PID
    WHERE F.PID IS NULL
)

SELECT * 
FROM S
ORDER BY ITEM_ID DESC