-- 코드를 입력하세요
WITH FORMAT_CHANGE AS(
    SELECT ORDER_ID,PRODUCT_ID,DATE_FORMAT(OUT_DATE, '%Y-%m-%d') AS OUT_DATE
    FROM FOOD_ORDER
)

SELECT ORDER_ID,PRODUCT_ID,OUT_DATE,
(CASE
    WHEN OUT_DATE <= '2022-05-01' THEN '출고완료'
    WHEN OUT_DATE > '2022-05-01' THEN '출고대기'
    ELSE '출고미정'
END) AS 출고여부
FROM FORMAT_CHANGE
ORDER BY ORDER_ID

