-- 코드를 입력하세요
WITH DtoAp AS(
    SELECT D.DR_NAME, A.APNT_YMD, A.APNT_NO, A.PT_NO, A.MCDP_CD
    FROM DOCTOR AS D JOIN APPOINTMENT AS A ON D.DR_ID = A.MDDR_ID
    WHERE A.APNT_CNCL_YN = 'N'
), PtoAp AS(
    SELECT DtoAp.APNT_NO, PATIENT.PT_NAME, DtoAp.PT_NO, DtoAp.MCDP_CD,DtoAp.DR_NAME,DtoAp.APNT_YMD
    FROM DtoAp JOIN PATIENT ON DtoAp.PT_NO = PATIENT.PT_NO
)

SELECT * 
FROM PtoAp
WHERE APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59'
ORDER BY APNT_YMD