-- 코드를 입력하세요
SELECT
   r1.ID,
   r1.START_TIME,
   r1.END_TIME
FROM
   RESERVATION r1
WHERE NOT EXISTS (
    SELECT 1
    FROM RESERVATION r2
    WHERE r1.ID <> r2.ID
    AND r1.START_TIME < r2.END_TIME
    AND r1.END_TIME > r2.START_TIME
    AND r2.ID < r1.ID
)
ORDER BY
    r1.START_TIME;